version: "3.3"

services:
  app:
    restart: always
    build: .
    container_name: springRestApplication
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/socks
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aq1sw2de34
      POSTGRES_DB: socks
    ports:
      - "5432:5432"